In [103]:
import pandas as pd 
data=pd.read_csv("/content/dataset.csv")
data

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [104]:
data=data[['Marital status','Course','Daytime/evening attendance','Previous qualification','Displaced','Educational special needs','Debtor','Tuition fees up to date','Scholarship holder']]


In [6]:
data.columns

Index(['Marital status', 'Course', 'Daytime/evening attendance',
       'Previous qualification', 'Displaced', 'Educational special needs',
       'Debtor', 'Tuition fees up to date', 'Scholarship holder'],
      dtype='object')

In [27]:
import numpy as np

decision_matrix=np.array([[1.        , 0.14285714, 0.25      , 0.33333333, 0.11111111,
        1.        , 0.11111111, 0.125     , 0.11111111],
       [7.        , 1.        , 0.14285714, 0.25      , 0.2       ,
        0.2       , 0.33333333, 0.11111111, 1.        ],
       [4.        , 7.        , 1.        , 0.25      , 0.11111111,
        0.25      , 0.2       , 0.14285714, 0.33333333],
       [3.        , 4.        , 4.        , 1.        , 0.125     ,
        0.5       , 1.        , 0.25      , 1.        ],
       [9.        , 5.        , 9.        , 8.        , 1.        ,
        1.        , 0.25      , 0.16666667, 0.25      ],
       [1.        , 5.        , 4.        , 2.        , 1.        ,
        1.        , 0.2       , 0.33333333, 0.33333333],
       [9.        , 3.        , 5.        , 1.        , 4.        ,
        5.        , 1.        , 0.14285714, 0.25      ],
       [8.        , 9.        , 7.        , 4.        , 6.        ,
        3.        , 7.        , 1.        , 0.11111111],
       [9.        , 1.        , 3.        , 1.        , 4.        ,
        3.        , 4.        , 9.        , 1.        ]])
import pandas as pd 
pd.DataFrame(decision_matrix)

0         1         2         3         4     5         6         7  \
0  1.0  0.142857  0.250000  0.333333  0.111111  1.00  0.111111  0.125000   
1  7.0  1.000000  0.142857  0.250000  0.200000  0.20  0.333333  0.111111   
2  4.0  7.000000  1.000000  0.250000  0.111111  0.25  0.200000  0.142857   
3  3.0  4.000000  4.000000  1.000000  0.125000  0.50  1.000000  0.250000   
4  9.0  5.000000  9.000000  8.000000  1.000000  1.00  0.250000  0.166667   
5  1.0  5.000000  4.000000  2.000000  1.000000  1.00  0.200000  0.333333   
6  9.0  3.000000  5.000000  1.000000  4.000000  5.00  1.000000  0.142857   
7  8.0  9.000000  7.000000  4.000000  6.000000  3.00  7.000000  1.000000   
8  9.0  1.000000  3.000000  1.000000  4.000000  3.00  4.000000  9.000000   

          8  
0  0.111111  
1  1.000000  
2  0.333333  
3  1.000000  
4  0.250000  
5  0.333333  
6  0.250000  
7  0.111111  
8  1.000000

In [105]:
data=data[:200]
data

Marital status  Course  Daytime/evening attendance  \
0                 1       2                           1   
1                 1      11                           1   
2                 1       5                           1   
3                 1      15                           1   
4                 2       3                           0   
..              ...     ...                         ...   
195               1      17                           0   
196               1      12                           1   
197               1       7                           1   
198               1      16                           1   
199               1      12                           1   

     Previous qualification  Displaced  Educational special needs  Debtor  \
0                         1          1                          0       0   
1                         1          1                          0       0   
2                         1          1                          0       0   
3                         1          1                          0       0   
4                         1          0                          0       0   
..                      ...        ...                        ...     ...   
195                      15          1                          0       0   
196                       1          1                          0       0   
197                       3          0                          0       0   
198                       1          0                          0       0   
199                       1          0                          0       0   

     Tuition fees up to date  Scholarship holder  
0                          1                   0  
1                          0                   0  
2                          0                   0  
3                          1                   0  
4                          1                   0  
..                       ...                 ...  
195                        1                   0  
196                        1                   0  
197                        1                   0  
198                        1                   0  
199                        1                   0  

[200 rows x 9 columns]

In [9]:
data['Marital status'].unique()

array([1, 2, 4, 3])

**Alternative Matrices**


First Cretirea: Marital status

In [10]:
import numpy as np
import pandas as pd
matrix_c1=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Marital status'].values[i]==data['Marital status'].values[j]):
      matrix_c1[i,j]=1
    elif (data['Marital status'].values[i]==1 or data['Marital status'].values[i]==4 or data['Marital status'].values[i]==5 or data['Marital status'].values[i]==6 ):
       matrix_c1[i,j]=2
    else:
       matrix_c1[i,j]=0.5

matrix_c1
df=pd.DataFrame(matrix_c1)
df

0    1    2    3    4    5    6    7    8    9    ...  190  191  192  \
0    1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
1    1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
2    1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
3    1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
4    0.5  0.5  0.5  0.5  1.0  1.0  0.5  0.5  0.5  0.5  ...  0.5  0.5  0.5   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
195  1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
196  1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
197  1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
198  1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
199  1.0  1.0  1.0  1.0  2.0  2.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   

     193  194  195  196  197  198  199  
0    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
1    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
2    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
3    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
4    0.5  0.5  0.5  0.5  0.5  0.5  0.5  
..   ...  ...  ...  ...  ...  ...  ...  
195  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
196  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
197  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
198  1.0  1.0  1.0  1.0  1.0  1.0  1.0  
199  1.0  1.0  1.0  1.0  1.0  1.0  1.0  

[200 rows x 200 columns]

Second Criteria: Course

In [11]:
matrix_c2=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Course'].values[i]==data['Course'].values[j]):
      matrix_c2[i,j]=1
    elif (data['Course'].values[i]==1 or data['Course'].values[i]==4 or data['Course'].values[i]==6 or data['Course'].values[i]==7 or data['Course'].values[i]==12 or data['Course'].values[i]==13 or data['Course'].values[i]==15 or data['Course'].values[i]==16):
       matrix_c2[i,j]=0.5
    else:
       matrix_c2[i,j]=2

matrix_c2

array([[1. , 2. , 2. , ..., 2. , 2. , 2. ],
       [2. , 1. , 2. , ..., 2. , 2. , 2. ],
       [2. , 2. , 1. , ..., 2. , 2. , 2. ],
       ...,
       [0.5, 0.5, 0.5, ..., 1. , 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 1. , 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 1. ]])

Third criteria: Previous qualification

In [12]:
matrix_c3=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Previous qualification'].values[i]==data['Previous qualification'].values[j]):
      matrix_c3[i,j]=1
    elif (data['Previous qualification'].values[i]==2 or data['Previous qualification'].values[i]==3 or data['Previous qualification'].values[i]==4 or data['Previous qualification'].values[i]==17 or data['Previous qualification'].values[i]==14 ):
       matrix_c3[i,j]=1.5
    elif (data['Previous qualification'].values[i]==5):
      matrix_c3[i,j]=0.5
    else:
       matrix_c3[i,j]=3

matrix_c3

array([[1. , 1. , 1. , ..., 3. , 1. , 1. ],
       [1. , 1. , 1. , ..., 3. , 1. , 1. ],
       [1. , 1. , 1. , ..., 3. , 1. , 1. ],
       ...,
       [1.5, 1.5, 1.5, ..., 1. , 1.5, 1.5],
       [1. , 1. , 1. , ..., 3. , 1. , 1. ],
       [1. , 1. , 1. , ..., 3. , 1. , 1. ]])

4th criteria: Daytime/evening attendance

In [13]:
matrix_c4=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Daytime/evening attendance'].values[i]==data['Daytime/evening attendance'].values[j]):
      matrix_c4[i,j]=1
    elif (data['Daytime/evening attendance'].values[i]==1 ):
       matrix_c4[i,j]=2
    
    else:
       matrix_c4[i,j]=1.5

matrix_c4

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

5th criteria: Displaced

In [14]:
matrix_c5=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Displaced'].values[i]==data['Displaced'].values[j]):
      matrix_c5[i,j]=1
    elif (data['Displaced'].values[i]==1 ):
       matrix_c5[i,j]=1.5
    
    else:
       matrix_c5[i,j]=3

matrix_c5

array([[1. , 1. , 1. , ..., 1.5, 1.5, 1.5],
       [1. , 1. , 1. , ..., 1.5, 1.5, 1.5],
       [1. , 1. , 1. , ..., 1.5, 1.5, 1.5],
       ...,
       [3. , 3. , 3. , ..., 1. , 1. , 1. ],
       [3. , 3. , 3. , ..., 1. , 1. , 1. ],
       [3. , 3. , 3. , ..., 1. , 1. , 1. ]])

6th criteria: Educational special needs

In [15]:
matrix_c6=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Educational special needs'].values[i]==data['Educational special needs'].values[j]):
      matrix_c6[i,j]=1
    elif (data['Educational special needs'].values[i]==1 ):
       matrix_c6[i,j]=1.5
    
    else:
       matrix_c6[i,j]=3

matrix_c6

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

7th criteria: Tuition fees up to date

In [16]:
matrix_c7=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Tuition fees up to date'].values[i]==data['Tuition fees up to date'].values[j]):
      matrix_c7[i,j]=1
    elif (data['Tuition fees up to date'].values[i]==0 ):
       matrix_c7[i,j]=1.5
    
    else:
       matrix_c7[i,j]=3

matrix_c7

array([[1. , 3. , 3. , ..., 1. , 1. , 1. ],
       [1.5, 1. , 1. , ..., 1.5, 1.5, 1.5],
       [1.5, 1. , 1. , ..., 1.5, 1.5, 1.5],
       ...,
       [1. , 3. , 3. , ..., 1. , 1. , 1. ],
       [1. , 3. , 3. , ..., 1. , 1. , 1. ],
       [1. , 3. , 3. , ..., 1. , 1. , 1. ]])

8th criteria: Scholarship holder

In [17]:
matrix_c8=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Scholarship holder'].values[i]==data['Scholarship holder'].values[j]):
      matrix_c8[i,j]=1
    elif (data['Scholarship holder'].values[i]==0 ):
       matrix_c8[i,j]=1.5
    
    else:
       matrix_c8[i,j]=3

matrix_c8

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

9th criteria: Debtor

In [18]:
matrix_c9=np.zeros((200,200))
for i in range(200):
  for  j in range (200):
    if(data['Debtor'].values[i]==data['Debtor'].values[j]):
      matrix_c9[i,j]=1
    elif (data['Debtor'].values[i]==1 ):
       matrix_c9[i,j]=1.5
    
    else:
       matrix_c9[i,j]=3

matrix_c9

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

**AHP method**

In [20]:
def normalizeMatrix(matrix):
    
    num_columns = len(matrix[0])
    column_sums = [sum(row[i] for row in matrix) for i in range(num_columns)]
    normalized_matrix = [[element/column_sums[col_index] for col_index, element in enumerate(row)] for row in matrix]

    return normalized_matrix

In [28]:
norm_mat=normalizeMatrix(decision_matrix)
norm_mat

[[0.0196078431372549,
  0.004065040569436181,
  0.007486631016683347,
  0.018691588601624592,
  0.00671478925723885,
  0.06688963210702341,
  0.007883326687546969,
  0.011089596908668934,
  0.025316455494311812],
 [0.13725490196078433,
  0.028455284555158965,
  0.004278074781114701,
  0.014018691591405362,
  0.012086620783896138,
  0.013377926421404684,
  0.023649980062640907,
  0.00985741937579819,
  0.2278481017272873],
 [0.0784313725490196,
  0.19918699188611275,
  0.02994652406673339,
  0.014018691591405362,
  0.00671478925723885,
  0.016722408026755852,
  0.014189988179484428,
  0.01267382478500228,
  0.07594936648293543],
 [0.058823529411764705,
  0.11382113822063586,
  0.11978609626693355,
  0.05607476636562145,
  0.007554137989935086,
  0.033444816053511704,
  0.07094994089742213,
  0.022179193817337867,
  0.2278481017272873],
 [0.17647058823529413,
  0.1422764227757948,
  0.2695187166006005,
  0.4485981309249716,
  0.06043310391948069,
  0.06688963210702341,
  0.01773748522435

In [31]:
def extract_weight_values(matrix):
    
    mat = normalizeMatrix(matrix)
    row_sums = [sum(row) for row in matrix]
    np_matrix = np.asarray(matrix)
    row_Averages = [element / np_matrix.shape[1] for element in row_sums]
    
    return row_Averages

In [32]:
extract_weight_values(norm_mat)

[0.018638322642198772,
 0.05231411125105451,
 0.049759328536076425,
 0.07894241341671664,
 0.13929691496962482,
 0.07120602708083831,
 0.13160113288081618,
 0.2245372641008513,
 0.23370448512182296]

In [49]:
alternative_matrices = matrices = [
    matrix_c1,
    matrix_c2,
    matrix_c3,
    matrix_c4,
    matrix_c5,
    matrix_c6,
    matrix_c7,
    matrix_c8,
    matrix_c9
]

In [51]:
def final_score(matrix, altMatrices):
    
    weights_list = [extract_weight_values(element) for element in altMatrices]
    
    priority_matrix = np.array(weights_list).transpose()
    
    matrix_weights = np.array(extract_weight_values(matrix)).transpose()
    
    return np.dot(priority_matrix,matrix_weights)
    

In [52]:
score = final_score(norm_mat,alternative_matrices)
score

array([1.19425974, 1.23052565, 1.23209507, 1.11997371, 1.35667594,
       1.49902356, 1.44614644, 1.23052565, 1.6589369 , 1.28498418,
       1.19425974, 1.44614644, 1.12049685, 1.60254146, 1.44248445,
       1.11997371, 1.19164404, 1.12337412, 1.19530603, 1.12049685,
       1.66155261, 1.11853507, 1.12337412, 1.51703206, 1.26789467,
       1.56992117, 1.19164404, 1.11971213, 1.19190561, 1.12337412,
       1.27588142, 1.19425974, 1.37426148, 1.22222009, 1.36700221,
       1.35613419, 1.20574468, 1.33642616, 1.2397221 , 1.44573095,
       1.31999907, 1.19190561, 1.15808706, 1.30232958, 1.36700221,
       1.36700221, 1.19164404, 1.44614644, 1.70207718, 1.6589369 ,
       1.65998319, 1.44614644, 1.44274602, 1.33982658, 1.36700221,
       1.12337412, 1.3400836 , 1.28238485, 1.12337412, 1.19425974,
       1.26789467, 1.67150113, 1.51703206, 1.19425974, 1.33878029,
       1.2271958 , 1.51703206, 1.13136087, 1.39193097, 1.33721087,
       1.33642616, 1.26789467, 1.19425974, 1.19269032, 1.11997

In [53]:
def rank(matrix):
    return sorted(list(matrix),reverse = True)

rank(score)

[1.7548927508659302,
 1.702338753198098,
 1.7020771826418428,
 1.6895129521864833,
 1.6715011348390691,
 1.6615526099462625,
 1.6615526099462625,
 1.6615526099462625,
 1.659983186608731,
 1.659983186608731,
 1.659198474939965,
 1.6589369043837097,
 1.6589369043837097,
 1.6427713871861982,
 1.6025414622658787,
 1.5906669892010836,
 1.5906669892010836,
 1.5906669892010836,
 1.5872665719697652,
 1.5699211703191571,
 1.5170320606652767,
 1.5170320606652767,
 1.5170320606652767,
 1.5170320606652767,
 1.515462637327745,
 1.5146779256589793,
 1.514416355102724,
 1.514416355102724,
 1.514416355102724,
 1.4990235582401836,
 1.4982508379052124,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4461464399200978,
 1.4457309464013368,
 1.4444156273972322,
 1.4432691638012898,
 1.4432691638012898,
 1.4427460226887794,
 1.4427460226887794,
 1.442484452132524,
 

In [42]:
def compute_CI(matrix):
    
    matrix_weights = np.array(extract_weight_values(matrix)).transpose()
    
    AW = [np.dot(row,matrix_weights) for row in matrix]
    
    Lambda = [aw / element for (aw,element) in zip(AW,matrix_weights)]
    
    m = max(Lambda)
    np_matrix = np.asarray(matrix)
    return (m-np_matrix.shape[0])/(np_matrix.shape[0]-1)

In [43]:
compute_CI(norm_mat)

-0.9476843672929713

In [40]:
def compute_CR(matrix, RI):
    
    CI = compute_CI(matrix)
    
    if RI !=0:
        CR = CI / RI 
    else:
        CR = 0
    return CR 

In [47]:
compute_CR(norm_mat,1.45)

-0.6535754257192906

**WSM&WPM**

In [57]:
binary_vect=np.array([0,0,1,0,0,0,0,0,1,1])
binary_vect

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1])

In [106]:
data=data.values
data

array([[ 1,  2,  1, ...,  0,  1,  0],
       [ 1, 11,  1, ...,  0,  0,  0],
       [ 1,  5,  1, ...,  0,  0,  0],
       ...,
       [ 1,  7,  1, ...,  0,  1,  0],
       [ 1, 16,  1, ...,  0,  1,  0],
       [ 1, 12,  1, ...,  0,  1,  0]])

In [121]:
import array
def normalization1(matrice,binary_vect):
  max_vect=np.amax(matrice, axis=0)
  min_vect=np.amin(matrice, axis=0)
  #max_min=matrice[5:7,]
  normal_matrix=[]
  for i in range (matrice.shape[1]):
    if binary_vect[i] ==1:
      #normal_matrix.append(matrice[:,i]/max_vect[i])
       normal_col  = np.divide(matrice[:, i], max_vect[i], out=np.zeros_like(matrice[:, i],dtype=np.float64), where=max_vect[i]!=0)
    else:
      normal_col=np.divide(min_vect[i], matrice[:, i], out=np.zeros_like(matrice[:, i],dtype=np.float64), where=matrice[:, i]!=0)

    normal_matrix.append(np.nan_to_num(normal_col))
  #return min_vect
  return np.array(normal_matrix).transpose()


  
norm_matrix=normalization1(data,binary_vect)       
norm_matrix

array([[1.        , 0.5       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.09090909, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.2       , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.14285714, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.0625    , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.08333333, 1.        , ..., 0.        , 0.        ,
        0.        ]])

In [3]:
weights=[0.111,0.111,0.111,0.111,0.111,0.111,0.111,0.111,0.111]

In [108]:
def WSM( normalized,weights):
  wsm_matrix=[]
  s=[]
  #weights=matrice[7:8,]
  for i in range (normalized.shape[1]):#col 
    wsm_matrix.append(weights[i]*normalized[:,i])
    
  
    #for j in range (normalized.shape[0]):
    #wsm_matrix.append(weights[i]*normalized[j,i])

  wsm_matrix=np.array(wsm_matrix).transpose()
  s=  np.sum(wsm_matrix,axis=1)
  return s


In [122]:
WSM(norm_matrix,weights)

array([0.3885    , 0.34309091, 0.3552    , 0.3404    , 0.2035    ,
       0.07127941, 0.45325   , 0.34309091, 0.4551    , 0.3441    ,
       0.34092857, 0.45325   , 0.3399375 , 0.35002841, 0.4625    ,
       0.3404    , 0.3441    , 0.34225   , 0.346875  , 0.3399375 ,
       0.4995    , 0.34153846, 0.34225   , 0.45192857, 0.34225   ,
       0.4551    , 0.3441    , 0.3515    , 0.34533333, 0.34225   ,
       0.25767857, 0.3552    , 0.34533333, 0.259     , 0.22852941,
       0.444     , 0.25173214, 0.34533333, 0.14527941, 0.24380357,
       0.3404    , 0.34533333, 0.34225   , 0.3404    , 0.22852941,
       0.22852941, 0.3441    , 0.45325   , 0.26692857, 0.4551    ,
       0.45409091, 0.45325   , 0.4514    , 0.346875  , 0.22852941,
       0.34225   , 0.21359091, 0.243275  , 0.34225   , 0.3885    ,
       0.34225   , 0.35202857, 0.4995    , 0.3552    , 0.3552    ,
       0.15725   , 0.4995    , 0.25767857, 0.34533333, 0.34309091,
       0.34533333, 0.34225   , 0.3885    , 0.34309091, 0.3404 

In [123]:
def WPM( normalized,weights):
  wpm_matrix=[]
  p=[]
  #weights=matrice[7:8,]
  for i in range (normalized.shape[1]):#col 
    wpm_matrix.append(normalized[:,i]**weights[i])
    
  
    #for j in range (normalized.shape[0]):
    #wsm_matrix.append(weights[i]*normalized[j,i])

  wpm_matrix=np.array(wpm_matrix).transpose()
  p=np.prod(wpm_matrix, axis=1)
  return p

WPM(norm_matrix,weights)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [124]:
produc_l=WPM(norm_matrix,weights)
sum_l=WSM(norm_matrix,weights)

In [125]:
def rank(l):
  return sorted(l,reverse=True)

In [127]:
rank(sum_l)

[0.4995,
 0.4995,
 0.4995,
 0.46249999999999997,
 0.4563333333333333,
 0.4563333333333333,
 0.4551,
 0.4551,
 0.4551,
 0.4551,
 0.4551,
 0.4551,
 0.4540909090909091,
 0.4540909090909091,
 0.4540909090909091,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.45325,
 0.4519285714285714,
 0.4519285714285714,
 0.4519285714285714,
 0.4519285714285714,
 0.4519285714285714,
 0.45139999999999997,
 0.45139999999999997,
 0.45139999999999997,
 0.45139999999999997,
 0.45139999999999997,
 0.4509375,
 0.4509375,
 0.444,
 0.3885,
 0.3885,
 0.3885,
 0.3885,
 0.3885,
 0.3885,
 0.37,
 0.3552,
 0.3552,
 0.3552,
 0.3552,
 0.3552,
 0.3552,
 0.3552,
 0.3552,
 0.3552,
 0.3520285714285714,
 0.3515,
 0.3515,
 0.3515,
 0.3515,
 0.3515,
 0.3515,
 0.3515,
 0.3515,
 0.3515,
 0.3500284090909091,
 0.34885714285714287,
 0.34885714285714287,
 0.346875,
 0.346875,
 0.346875,
 0.3453333333333333,
 0.3453333333333333,
 0.3453333333333333,
 0.3453333

**WASPASS**

In [128]:
def WASPASS(wsm,wpm):
  lamb=0.5
  wap=[]
 
 
  for i in range (len(wsm)): 
    for j in range(len(wpm)):
      wap.append(lamb*wsm[i]+(1-lamb)*wpm[j])
    
  
  
  return wap


In [129]:
def WASPASS1(wsm,wpm):
  lamb=0.5
  was=[]
  for s , p in zip(wsm, wpm):
    was.append(lamb*s+(1-lamb)*p)

  return was


In [130]:
WASPASS1(produc_l,sum_l)

[0.19425,
 0.17154545454545456,
 0.1776,
 0.1702,
 0.10175000000000001,
 0.03563970588235294,
 0.226625,
 0.17154545454545456,
 0.22755,
 0.17205,
 0.1704642857142857,
 0.226625,
 0.16996875,
 0.17501420454545455,
 0.23124999999999998,
 0.1702,
 0.17205,
 0.171125,
 0.1734375,
 0.16996875,
 0.24975,
 0.17076923076923076,
 0.171125,
 0.2259642857142857,
 0.171125,
 0.22755,
 0.17205,
 0.17575,
 0.17266666666666666,
 0.171125,
 0.12883928571428574,
 0.1776,
 0.17266666666666666,
 0.1295,
 0.11426470588235293,
 0.222,
 0.12586607142857145,
 0.17266666666666666,
 0.07263970588235294,
 0.12190178571428571,
 0.1702,
 0.17266666666666666,
 0.171125,
 0.1702,
 0.11426470588235293,
 0.11426470588235293,
 0.17205,
 0.226625,
 0.1334642857142857,
 0.22755,
 0.22704545454545455,
 0.226625,
 0.22569999999999998,
 0.1734375,
 0.11426470588235293,
 0.171125,
 0.10679545454545454,
 0.1216375,
 0.171125,
 0.19425,
 0.171125,
 0.1760142857142857,
 0.24975,
 0.1776,
 0.1776,
 0.078625,
 0.24975,
 0.12883

In [131]:
np.sum(decision_matrix, axis=0)

array([51.        , 35.14285714, 33.39285714, 17.83333333, 16.54722222,
       14.95      , 14.09444444, 11.27182539,  4.38888888])

**Entropy**

In [132]:
def normalizationEntropy(array):
  somme= np.sum(array, axis=0)
  normalized=[]
  #for elt,s in zip(array,somme):
  for i in range (array.shape[1]):

    normalized.append(array[:,i]/somme[i])
  return np.array(normalized).transpose()



In [139]:
normalized=normalizationEntropy(data)
pd.DataFrame(normalized).isnull().values.any()


False

In [143]:
def p(data):
  p_matrix=[]
  for i in range(data.shape[0]):
    #for j in range (data.shape[0]):
      p_matrix.append((data[i] + 1e-10)*(np.log(data[i]  + 1e-10)))
  s=  np.sum(p_matrix,axis=0)

    
  return  s

somme_p=p(normalized)

somme_p

array([-5.24742011e+00, -5.20166357e+00, -5.19849715e+00, -4.60950865e+00,
       -4.81218458e+00, -4.58114433e-07, -3.04452285e+00, -5.20948627e+00,
       -3.80666286e+00])

In [144]:
def entropy(ndata,somme):
  entrop_matrix=[]
  n=ndata.shape[1]
  m=ndata.shape[0]
  k=1/np.log(m)
  for elt in somme:
    entrop_matrix.append(-k*elt)
 

  return np.array(entrop_matrix)


entropy_list=entropy(normalized,somme_p)
entropy_list

array([9.90393694e-01, 9.81757644e-01, 9.81160016e-01, 8.69994818e-01,
       9.08247703e-01, 8.64641360e-08, 5.74620704e-01, 9.83234093e-01,
       7.18466373e-01])

In [145]:
def entr_ej(entropy_list,somme_p):

  entrop_matrix=[]

 
  
  for i in range(entropy_list.shape[0]):
    entrop_matrix.append(1-entropy_list[i])
  return np.array(entrop_matrix)


In [146]:
enter_ej_list=entr_ej(entropy_list,somme_p)
enter_ej_list

array([0.00960631, 0.01824236, 0.01883998, 0.13000518, 0.0917523 ,
       0.99999991, 0.4253793 , 0.01676591, 0.28153363])

In [147]:
def w_j(entr_ej_list):
  s=np.sum(entr_ej_list,axis=0)
  list_w=[]
  for i in range(len(entr_ej_list)):
    list_w.append(entr_ej_list[i]/s)
  return list_w

w_j(enter_ej_list)

[0.00482214052043641,
 0.009157235344268832,
 0.0094572305694006,
 0.06525955466104594,
 0.04605750277129067,
 0.501976522106148,
 0.21353043813966105,
 0.008416092537149969,
 0.14132328335059874]

**ELECTRE 2**

In [13]:
def discordance_matrix(dm, weights):
    num_alternatives, num_criteria = dm.shape
    D = np.zeros((num_alternatives, num_alternatives))
    for i in range(num_alternatives):
        for j in range(num_alternatives):
            if i == j:
                D[i,j] = 0
            else:
                discordance_values = []
                for k in range(num_criteria):
                    if dm[i,k] < dm[j,k]:
                        discordance_values.append(weights[k])
                if len(discordance_values) == 0:
                    D[i,j] = 0
                else:
                    D[i,j] = np.max(discordance_values) / np.sum(weights)
    return D
D = discordance_matrix(decision_matrix, weights)
D

array([[0.        , 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.        , 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.        , 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111, 0.        , 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.        , 0.11111111, 0.11111111, 0.11111111, 0.        ,
        0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.        , 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.        , 0.11111111, 0.11111111, 0.11111111],
       [0.        , 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.        , 0.11111111, 0.11111111],
       [0.        , 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.        , 0.11111111],


In [24]:
p = 0.4
q = 0.6

# Calculate net concordance and net discordance matrices
num_alternatives = decision_matrix.shape[0]
Ci = np.sum(C, axis=1) / num_alternatives
Di = np.zeros(num_alternatives)
for i in range(num_alternatives):
    Di[i] = np.max(D[:,i])

# Calculate outranking relation matrix
outranking_matrix = np.zeros((num_alternatives, num_alternatives))
for i in range(num_alternatives):
    for j in range(num_alternatives):
        if Ci[i] >= p and Di[j] <= q:
            outranking_matrix[i,j] = 1
        elif Ci[j] >= p and Di[i] <= q:
            outranking_matrix[j,i] = 1

degrees_of_outranking = np.sum(outranking_matrix, axis=1)
ranking = np.argsort(degrees_of_outranking)
print("Ranking of alternatives: ", ranking+1)
print(C)

Ranking of alternatives:  [1 2 3 4 5 6 7 8 9]
[[1.         0.44444444 0.33333333 0.11111111 0.11111111 0.22222222
  0.         0.11111111 0.        ]
 [0.55555556 1.         0.55555556 0.33333333 0.22222222 0.33333333
  0.11111111 0.11111111 0.22222222]
 [0.77777778 0.55555556 1.         0.22222222 0.22222222 0.44444444
  0.33333333 0.11111111 0.11111111]
 [0.88888889 0.77777778 0.77777778 1.         0.33333333 0.44444444
  0.55555556 0.11111111 0.44444444]
 [1.         0.77777778 0.77777778 0.66666667 1.         0.77777778
  0.66666667 0.44444444 0.44444444]
 [1.         0.66666667 0.77777778 0.66666667 0.55555556 1.
  0.44444444 0.11111111 0.33333333]
 [1.         0.88888889 0.77777778 0.66666667 0.55555556 0.55555556
  1.         0.33333333 0.66666667]
 [1.         0.88888889 0.88888889 0.88888889 0.55555556 0.88888889
  0.66666667 1.         0.66666667]
 [1.         1.         0.88888889 0.77777778 0.66666667 0.66666667
  0.66666667 0.44444444 1.        ]]
